### ISSUE TITLE
Conflict with Inline Dataview fields in Reading (Unless icons and Inline Dataview fields are placed in a table)

### ISSUE THREAD

**Issue by I-Pch** [aidenlx/obsidian-icon-shortcodes#41]
Hi there 😊 

So, I'm hitting a very strange bug with the plugin where there seems to be some conflicts with the inline dataview fields `(field_x::value)`.

The plugin doesn't render the icons in `Reading` **unless** both icons and inline dataview fields are placed in a table 🤔 .
It seems to work fine in `Live Preview` though 🤔 .

<img width="1360" alt="Icons shortcodes - Inline Dataview fields" src="https://user-images.githubusercontent.com/77828085/160244107-1b3de8c8-41cc-4ca0-adee-ee7289a778cf.png">

I'm on Mac + Obsidian `v0.14.2` + Icon Shortcodes `0.9.2`

And here's the markdown I used for the screenshot above : 
```
> [!quote]
> an icon :luc_lightbulb: some text :luc_lightbulb_off: (moon_illuminated::41%)
> 
> |1|2|3|
> |--|--|--| 
> |an icon :luc_lightbulb:| some text| :luc_lightbulb_off: (moon_illuminated::41%)|

an icon :luc_lightbulb: some text :luc_lightbulb_off: (moon_illuminated::41%)

|1|2|3|
|--|--|--| 
|an icon :luc_lightbulb:| some text| :luc_lightbulb_off: (moon_illuminated::41%)|
```

**Comment by I-Pch** [comment]
Just wanted to add that this is completely new and was working before 🤔 (before what I have no idea though 😅 ... sorry 😇 )

Here's a screenshot of an old daily note (in `Reading`) from a test vault (for the date 2022-03-15) where I used both icons and inline dataview fields in a table or not without any troubles 🤔 ...

<img width="801" alt="Working Icon Shortcodes" src="https://user-images.githubusercontent.com/77828085/160246924-391deaec-2bcc-49ba-bb4e-f3c413a9bdf2.png">

I tried to uninstall/re-install the plugin but it didn't change a thing

**Comment by I-Pch** [comment]
Another small addition, in case this could be useful 😇 ...

When using icons within the brand new Obsidian Callouts, the icons seems to be rendered if and only if there's some space between the line where there are icons and the inline dataview field(s).

<img width="670" alt="icon shortcodes and callouts" src="https://user-images.githubusercontent.com/77828085/160254866-111d2fd4-a317-4b43-8d5a-37675f49e1d8.png">

So I guess, something changed in the editor when Obsidian `v.0.14.0` (at least) was released for the insiders 🤔 (as this is when Callouts and Tables in LP appeared) 

Emojis though don't seem to be impacted (as far as I can tell)

**Comment by I-Pch** [comment]
> Just wanted to add that this is completely new and was working before 🤔 (before what I have no idea though 😅 ... sorry 😇 )
> 
> Here's a screenshot of an old daily note (in `Reading`) from a test vault (for the date 2022-03-15) where I used both icons and inline dataview fields in a table or not without any troubles 🤔 ...
> 
> <img alt="Working Icon Shortcodes" width="801" src="https://user-images.githubusercontent.com/77828085/160246924-391deaec-2bcc-49ba-bb4e-f3c413a9bdf2.png">
> 
> I tried to uninstall/re-install the plugin but it didn't change a thing

I should have added here (sorry 😔 ) that in the vault where I can still mix icons and inline dataview fields, I didn't updated Icon Shortcodes ... 

It's still coming from `Mac` + `Obsidian v.0.14.2` but `Icon Shortcodes 0.8.4`.

**Comment by aidenlx** [comment]
should be fixed with icon shortcode v0.9.5 and this PR is merged: https://github.com/blacksmithgu/obsidian-dataview/pull/1098

**Comment by NothingWorksToday** [comment]
Bug is there (again?)
Obsidian: v1.0.3
DataView: 0.5.47
Icon-Shortcodes: 0.9.7

Source-code-view:
![image](https://user-images.githubusercontent.com/69650589/208156907-f419a739-a298-40d8-a76f-cebaf44a4404.png)

Live-preview
![image](https://user-images.githubusercontent.com/69650589/208157073-2ffe5bd8-f9d7-43c8-abe7-5a7ae9f75b05.png)

Reading-view:
![image](https://user-images.githubusercontent.com/69650589/208157179-a6e582f3-5344-455e-a654-a61663a147e5.png)

**Comment by Iconca** [comment]
Hello, I'm having the same issue with not rendering icons in reading view, when it's in the same line with dataview inline field. Is there any chance that it will be fixed soon or is it too complicated? Sorry if I'm asking in a wrong place, but with all this cross-referencing on git hub I'm never really sure, where I should post.

**Comment by I-Pch** [comment]
Hi @Iconca 😊 !

Well, this specific issue was closed (and I don't have troubles using icons and inline dataview fields within callouts/admonitions) but, you could probably add info to this other issue here -> #54 (as it's still opened) 😊.

**Comment by Iconca** [comment]
Hello. After your comment I've thought that after all,  it may be only my problem caused by some CSS. So I've checked in a Sandbox Volt and it still occurs. I'll make sure to ask in the thread that you pointed out. Thank you  for the reply.
